export const ENV = {
  appId: process.env.VITE_APP_ID ?? "mindprint-app",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  isProduction: process.env.NODE_ENV === "production",
  appUrl: process.env.APP_URL ?? "http://localhost:3000",
  // Legacy Manus fields — kept for unused helper files, not used by core app
  forgeApiUrl: "",
  forgeApiKey: "",
  oAuthServerUrl: "",
  ownerOpenId: "",
  lemonsqueezyApiKey: process.env.LEMONSQUEEZY_API_KEY ?? "",
  lemonsqueezyStoreId: process.env.LEMONSQUEEZY_STORE_ID ?? "",
  lemonsqueezyVariantId: process.env.LEMONSQUEEZY_VARIANT_ID ?? "",
  lemonsqueezyCheckoutUrl: process.env.LEMONSQUEEZY_CHECKOUT_URL ?? "",
  lemonsqueezyCheckoutUrlYearly: process.env.LEMONSQUEEZY_CHECKOUT_URL_YEARLY ?? "",
  lemonsqueezyWebhookSecret: process.env.LEMONSQUEEZY_WEBHOOK_SECRET ?? "",
};
